[keybindings]
w = "job:webserver"
q = "job:styles"

[jobs.webserver]
command = ["cargo", "run"]
need_stdout = true
background = false
on_change_strategy = "kill_then_restart"
kill = ["kill", "-s", "INT"]
watch = ["templates"]

[jobs.styles]
command = ["npx", "@tailwindcss/cli", "-i", "./src/input.css", "-o", "./src/public/style.css"]
allow_warnings = true
need_stdout = true
