services:
  db:
    image: postgres:17.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: promptdb
      POSTGRES_USER: promptuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # app:
  #   build: .
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   env_file: .env
  #   ports:
  #     - "3000:3000"

volumes:
  db_data:
